# Generated by Django 2.1.5 on 2019-02-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imputer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imputermember',
            name='oh_id',
            field=models.CharField(max_length=16),
        ),
    ]
