# Generated by Django 2.1.7 on 2019-03-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imputer', '0003_imputermember_data_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imputermember',
            name='data_source_id',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
