# Generated by Django 2.1.7 on 2019-06-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imputer', '0004_auto_20190328_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='imputermember',
            name='variant_length',
            field=models.IntegerField(default=1000),
        ),
    ]
