# Generated by Django 2.0.4 on 2018-04-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('open_humans', '0002_auto_20180409_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='open_humans.OpenHumansMember')),
            ],
        ),
    ]
