# Generated by Django 2.0.2 on 2018-03-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datauploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openhumansmember',
            name='user',
        ),
        migrations.DeleteModel(
            name='OpenHumansMember',
        ),
    ]
